# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1145, 822)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.line1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line1.setObjectName("line1")
        self.horizontalLayout.addWidget(self.line1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.age = QtWidgets.QLabel(self.centralwidget)
        self.age.setObjectName("age")
        self.horizontalLayout_2.addWidget(self.age)
        self.line2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line2.setObjectName("line2")
        self.horizontalLayout_2.addWidget(self.line2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.OK = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/qianzhui/IMG_1243.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OK.setIcon(icon)
        self.OK.setObjectName("OK")
        self.verticalLayout_2.addWidget(self.OK)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.text = QtWidgets.QTextEdit(self.centralwidget)
        self.text.setObjectName("text")
        self.horizontalLayout_4.addWidget(self.text)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.OK.clicked.connect(MainWindow.p1_ck)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.age.setText(_translate("MainWindow", "Age"))
        self.OK.setText(_translate("MainWindow", "OK"))
