# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QBasicTimer

from PyQt5.QtWidgets import *


class ProgressBar(QWidget):
    def __init__(self, parent=None):
        super.__init__()
        self.setWindowTitle("进度条")
        self.setGeometry(0, 0, 1600, 900)
        self.pbar = QProgressBar(self)
        self.pbar.setGeometry(50, 50, 200, 25)


        # self.button = QtWidgets.QPushButton('Start', self)
        # # self.button.setFocusPolicy(Qt.NoFocus)
        # self.button.move(40, 80)
        #
        # self.button.clicked.connect(self.onStart)
        self.timer = QBasicTimer()
        self.step = 0
        # self.onStart()

    def timerEvent(self, event):
        if self.step >= 100:
            self.step = 0
        self.step = self.step + 1
        self.pbar.setValue(self.step)

    def onStart(self):
        self.timer.start(10, self)
            # self.button.setText('Stop')

    def onStop(self):
        self.timer.stop()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 180, 93, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(self.doAction)



        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def doAction(self ):
        self.pgb = ProgressBar(None)
        self.pgb.show()
        # self.pgb.exec_()
        self.pgb.onStart()
        # func
        for i in range( 1000000 ):
            print( i )

        self.pgb.onStop()
        self.pgb.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "开始"))
