# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHBoxLayout, QLabel, QLineEdit, QToolButton


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(190, 90, 271, 301))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 80, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.YanshisLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.YanshisLayout.setContentsMargins(0, 0, 0, 0)
        self.YanshisLayout.setObjectName("YanshisLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 190, 93, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.Yanshis_add)
        # # 初始化全局命名空间
        self.names = globals()
        # # 获取YanshiLayout中子Layout的数量
        # self.count = self.YanshisLayout.count()

        # # 新建一个水平布局的子Layout
        # self.names["Yanshi_layout_{}".format(self.count + 1)] = QHBoxLayout(self)
        #
        # # 将新建的Layout添加到UI已有YanshiLayout中
        # self.YanshisLayout.addLayout(self.names["Yanshi_layout_{}".format(self.count + 1)])

    def Yanshis_add(self):
        # names = globals()
        count = self.YanshisLayout.count()
        # 在新建的Layout中动态地添加控件
        self.names["Yanshi_label_{}".format(count + 1)] = QLabel("Yanshi{}:".format(count + 1))
        self.names["Yanshi_label_{}".format(count + 1)].setText( "Yanshi_label_{}".format(count + 1))
        self.names["Yanshi_lineEdit_{}".format(count + 1)] = QLineEdit(self)
        self.names["Yanshi_Button_{}".format(count + 1)] = QToolButton(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
