# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_sw.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pymysql
from PyQt5.QtCore import QUrl, QObject, pyqtSignal, QCoreApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
from PyQt5.QtWidgets import QMessageBox, QMainWindow, QWidget, QLineEdit, QSizePolicy

import cos
import data_process
import qiangdu
import glgl
import sankey


# ### 自定义信号槽，可实现带参槽函数
# 信号对象

class QTypeSignal(QObject):
    # 定义一个信号
    sendmsg = pyqtSignal(object, object)

    def __init__(self):
        super(QTypeSignal, self).__init__()


# def run(self):
# 	# 发射信号
# 	self.sendmsg.emit([1,2,3,4],[11,12,12,34])
X = []
Y = []


# 槽对象
class QTypeSlot(QObject):
    def __init__(self):
        super(QTypeSlot, self).__init__()

    # 槽对象里的槽函数
    def get(self, x=[], y=[]):
        global X, Y
        X = x
        Y = y


class Ui_MainWindow(object):
    x, y = [], []
    db,tb,user,pwd = "","","",""
    isconnected = False
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 898)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        # self.tabWidget.tabBar().hide() # 可隐藏切换键
        self.tabWidget.setCurrentIndex(0)  # 默认显示第0个tab

        # ## tab_0 参数传递 数据处理
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.data_process_button = QtWidgets.QPushButton(self.tab_0)
        self.data_process_button.setGeometry(QtCore.QRect(500, 670, 189, 28))
        self.data_process_button.setObjectName("data_process_button")
        self.connect_button = QtWidgets.QPushButton(self.tab_0)
        self.connect_button.setGeometry(QtCore.QRect(140, 330, 93, 28))
        self.connect_button.setObjectName("connect_button")
        self.connect_button.clicked.connect( self.connect_database )
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_0)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 50, 281, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.db_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.db_lbl.setObjectName("db_lbl")
        self.horizontalLayout_2.addWidget(self.db_lbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.db_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.db_ledt.setObjectName("db_ledt")
        self.horizontalLayout_2.addWidget(self.db_ledt)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.tb_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.tb_lbl.setObjectName("tb_lbl")
        self.horizontalLayout_7.addWidget(self.tb_lbl)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.tb_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.tb_ledt.setObjectName("tb_ledt")
        self.horizontalLayout_7.addWidget(self.tb_ledt)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.user_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.user_lbl.setObjectName("user_lbl")
        self.horizontalLayout_8.addWidget(self.user_lbl)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.user_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.user_ledt.setObjectName("user_ledt")
        self.horizontalLayout_8.addWidget(self.user_ledt)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.pwd_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.pwd_lbl.setObjectName("pwd_lbl")
        self.horizontalLayout_9.addWidget(self.pwd_lbl)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.pwd_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pwd_ledt.setObjectName("pwd_ledt")
        self.pwd_ledt.setEchoMode(QLineEdit.Password)
        self.horizontalLayout_9.addWidget(self.pwd_ledt)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.group_lda = QtWidgets.QGroupBox(self.tab_0)
        self.group_lda.setGeometry(QtCore.QRect(440, 30, 351, 331))
        self.group_lda.setObjectName("group_lda")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.group_lda)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 30, 291, 271))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.lda_year1_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lda_year1_lbl.setObjectName("lda_year1_lbl")
        self.horizontalLayout_3.addWidget(self.lda_year1_lbl)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.lda_year1_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lda_year1_ledt.setObjectName("lda_year1_ledt")
        self.horizontalLayout_3.addWidget(self.lda_year1_ledt)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.lda_year2_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lda_year2_lbl.setObjectName("lda_year2_lbl")
        self.horizontalLayout_10.addWidget(self.lda_year2_lbl)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        self.lda_year2_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lda_year2_ledt.setObjectName("lda_year2_ledt")
        self.horizontalLayout_10.addWidget(self.lda_year2_ledt)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.lda_attr_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lda_attr_lbl.setObjectName("lda_attr_lbl")
        self.horizontalLayout_11.addWidget(self.lda_attr_lbl)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem19)
        self.lda_attr_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lda_attr_ledt.setObjectName("lda_attr_ledt")
        self.horizontalLayout_11.addWidget(self.lda_attr_ledt)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem21)
        self.lda_n_topics_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lda_n_topics_lbl.setObjectName("lda_n_topics_lbl")
        self.horizontalLayout_12.addWidget(self.lda_n_topics_lbl)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem22)
        self.lda_n_topics_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lda_n_topics_ledt.setObjectName("lda_n_topics_ledt")
        self.horizontalLayout_12.addWidget(self.lda_n_topics_ledt)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem23)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem24)
        self.lda_n_top_words_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lda_n_top_words_lbl.setObjectName("lda_n_top_words_lbl")
        self.horizontalLayout_13.addWidget(self.lda_n_top_words_lbl)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem25)
        self.lda_n_top_words_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lda_n_top_words_ledt.setObjectName("lda_n_top_words_ledt")
        self.horizontalLayout_13.addWidget(self.lda_n_top_words_ledt)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem26)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.group_lda_2 = QtWidgets.QGroupBox(self.tab_0)
        self.group_lda_2.setGeometry(QtCore.QRect(440, 390, 351, 101))
        self.group_lda_2.setObjectName("group_lda_2")
        self.layoutWidget = QtWidgets.QWidget(self.group_lda_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 291, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem27)
        self.p_n_max_topics_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.p_n_max_topics_lbl.setObjectName("p_n_max_topics_lbl")
        self.horizontalLayout_4.addWidget(self.p_n_max_topics_lbl)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem28)
        self.p_n_max_topics_ledt = QtWidgets.QLineEdit(self.layoutWidget)
        self.p_n_max_topics_ledt.setObjectName("p_n_max_topics_ledt")
        self.horizontalLayout_4.addWidget(self.p_n_max_topics_ledt)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem29)
        self.group_lda_3 = QtWidgets.QGroupBox(self.tab_0)
        self.group_lda_3.setGeometry(QtCore.QRect(820, 30, 351, 381))
        self.group_lda_3.setObjectName("group_lda_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.group_lda_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 30, 291, 321))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem30)
        self.qd_year1_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.qd_year1_lbl.setObjectName("qd_year1_lbl")
        self.horizontalLayout_5.addWidget(self.qd_year1_lbl)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem31)
        self.qd_year1_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.qd_year1_ledt.setObjectName("qd_year1_ledt")
        self.horizontalLayout_5.addWidget(self.qd_year1_ledt)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem32)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem33)
        self.qd_year2_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.qd_year2_lbl.setObjectName("qd_year2_lbl")
        self.horizontalLayout_15.addWidget(self.qd_year2_lbl)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem34)
        self.qd_year2_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.qd_year2_ledt.setObjectName("qd_year2_ledt")
        self.horizontalLayout_15.addWidget(self.qd_year2_ledt)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem35)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem36)
        self.qd_year3_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.qd_year3_lbl.setObjectName("qd_year3_lbl")
        self.horizontalLayout_16.addWidget(self.qd_year3_lbl)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem37)
        self.qd_year3_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.qd_year3_ledt.setObjectName("qd_year3_ledt")
        self.horizontalLayout_16.addWidget(self.qd_year3_ledt)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem38)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem39)
        self.qd_year4_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.qd_year4_lbl.setObjectName("qd_year4_lbl")
        self.horizontalLayout_17.addWidget(self.qd_year4_lbl)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem40)
        self.qd_year4_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.qd_year4_ledt.setObjectName("qd_year4_ledt")
        self.horizontalLayout_17.addWidget(self.qd_year4_ledt)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem41)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem42)
        self.qd_dur_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.qd_dur_lbl.setObjectName("qd_dur_lbl")
        self.horizontalLayout_6.addWidget(self.qd_dur_lbl)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem43)
        self.qd_dur_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.qd_dur_ledt.setObjectName("qd_dur_ledt")
        self.horizontalLayout_6.addWidget(self.qd_dur_ledt)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem44)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem45)
        self.qd_n_topics_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.qd_n_topics_lbl.setObjectName("qd_n_topics_lbl")
        self.horizontalLayout_18.addWidget(self.qd_n_topics_lbl)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem46)
        self.qd_n_topics_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.qd_n_topics_ledt.setObjectName("qd_n_topics_ledt")
        self.horizontalLayout_18.addWidget(self.qd_n_topics_ledt)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem47)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.group_lda_4 = QtWidgets.QGroupBox(self.tab_0)
        self.group_lda_4.setGeometry(QtCore.QRect(1200, 40, 351, 711))
        self.group_lda_4.setObjectName("group_lda_4")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.group_lda_4)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 30, 291, 161))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem48)
        self.cos_attr_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.cos_attr_lbl.setObjectName("cos_attr_lbl")
        self.horizontalLayout_19.addWidget(self.cos_attr_lbl)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem49)
        self.cos_attr_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.cos_attr_ledt.setObjectName("cos_attr_ledt")
        self.horizontalLayout_19.addWidget(self.cos_attr_ledt)
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem50)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem51)
        self.cos_n_topics_1_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.cos_n_topics_1_lbl.setObjectName("cos_n_topics_1_lbl")
        self.horizontalLayout_20.addWidget(self.cos_n_topics_1_lbl)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem52)
        self.cos_n_topics_1_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.cos_n_topics_1_ledt.setObjectName("cos_n_topics_1_ledt")
        self.horizontalLayout_20.addWidget(self.cos_n_topics_1_ledt)
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem53)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem54)
        self.cos_n_topics_2_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.cos_n_topics_2_lbl.setObjectName("cos_n_topics_2_lbl")
        self.horizontalLayout_21.addWidget(self.cos_n_topics_2_lbl)
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem55)
        self.cos_n_topics_2_ledt = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.cos_n_topics_2_ledt.setObjectName("cos_n_topics_2_ledt")
        self.horizontalLayout_21.addWidget(self.cos_n_topics_2_ledt)
        spacerItem56 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem56)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)

        self.verticalLayoutWidget = QtWidgets.QWidget(self.group_lda_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 220, 160, 300))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.time_window_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.time_window_layout.setContentsMargins(0, 0, 0, 0)
        self.time_window_layout.setObjectName("time_window_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.label_5.setSizePolicy(QSizePolicy.Preferred,QSizePolicy.Fixed)
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem57 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem57)
        self.time_window_layout.addLayout(self.horizontalLayout)
        self.interval_layout_1 = QtWidgets.QHBoxLayout()
        self.interval_layout_1.setObjectName("interval_layout_1")
        spacerItem58 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.interval_layout_1.addItem(spacerItem58)
        self.count = 1
        self.lineEdit_begin = globals()
        self.lineEdit_begin["lineEdit_begin_{}".format(self.count)] = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_begin["lineEdit_begin_{}".format(self.count )].setObjectName("lineEdit_begin_{}".format(self.count))
        self.interval_layout_1.addWidget(self.lineEdit_begin["lineEdit_begin_{}".format(self.count )])
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.interval_layout_1.addItem(spacerItem59)
        self.lbl_ = globals()
        self.lbl_["lbl_{}".format(self.count)] = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_["lbl_{}".format(self.count)].setObjectName(
            "lbl_{}".format(self.count))
        self.interval_layout_1.addWidget(self.lbl_["lbl_{}".format(self.count)])
        spacerItem60 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.interval_layout_1.addItem(spacerItem60)
        self.lineEdit_end = globals()
        self.lineEdit_end["lineEdit_end_{}".format(self.count)] = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_end["lineEdit_end_{}".format(self.count)].setObjectName(
            "lineEdit_end_{}".format(self.count))
        self.interval_layout_1.addWidget(self.lineEdit_begin["lineEdit_end_{}".format(self.count)])
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.interval_layout_1.addItem(spacerItem61)
        # self.lineEdit_8.setAlignment( QtCore.Qt.AlignTop ) # 完全没啥用
        # self.lineEdit_9.setAlignment(QtCore.Qt.AlignTop)
        # self.label_12.setAlignment(QtCore.Qt.AlignTop)
        self.time_window_layout.addLayout(self.interval_layout_1)
        self.add_button = QtWidgets.QPushButton(self.group_lda_4)
        self.add_button.setGeometry(QtCore.QRect(200, 270, 21, 21))
        self.add_button.setObjectName("add_button")
        self.add_button.clicked.connect( self.add_interval )
        self.tabWidget.addTab(self.tab_0, "")

        # ## tab_1: lda、困惑度
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.perplexity_button = QtWidgets.QPushButton(self.tab_1)
        self.perplexity_button.setGeometry(QtCore.QRect(1270, 740, 185, 30))
        self.perplexity_button.setObjectName("perplexity_button")
        self.lda_button = QtWidgets.QPushButton(self.tab_1)
        self.lda_button.setGeometry(QtCore.QRect(1030, 740, 185, 30))
        self.lda_button.setObjectName("lda_button")
        # self.data_process_button = QtWidgets.QPushButton(self.tab_1)
        # self.data_process_button.setGeometry(QtCore.QRect(980, 760, 185, 30))
        # self.data_process_button.setObjectName("data_process_button")
        # 创建web窗体
        self.browser = QWebEngineView(self.tab_1)
        self.browser.setGeometry(QtCore.QRect(20, 30, 890, 780))
        self.browser.setObjectName("web_browser")
        self.lda_button.clicked.connect(self.show_web)
        # pyqtgraph
        self.pw1 = pg.PlotWidget(self.tab_1)
        self.pw1.setGeometry(QtCore.QRect(930, 30, 630, 700))
        self.pw1.setObjectName("pw1")
        # self.label_2 = QtWidgets.QLabel(self.tab_1)
        # self.label_2.setGeometry(QtCore.QRect(930, 30, 631, 701))
        # self.label_2.setObjectName("label_2")
        self.data_process_button.clicked.connect(self.process_1)
        self.perplexity_button.clicked.connect(self.show_perplexity)
        self.tabWidget.addTab(self.tab_1, "")

        # ## 主题强度
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.qiangdu_button = QtWidgets.QPushButton(self.tab_2)
        self.qiangdu_button.setGeometry(QtCore.QRect(90, 740, 171, 41))
        self.qiangdu_button.setObjectName("qiangdu_button")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(100, 80, 1391, 601))
        self.label_3.setObjectName("label_3")
        self.qiangdu_button.clicked.connect(self.process_2)
        self.tabWidget.addTab(self.tab_2, "")

        # ## 余弦相似度
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.cos_button = QtWidgets.QPushButton(self.tab_3)
        self.cos_button.setGeometry(QtCore.QRect(60, 730, 171, 41))
        self.cos_button.setObjectName("cos_button")
        self.cos_button.clicked.connect(self.process_3)
        self.tabWidget.addTab(self.tab_3, "")

        # ## 关联规则 桑基图
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.sankey_button = QtWidgets.QPushButton(self.tab_4)
        self.sankey_button.setGeometry(QtCore.QRect(240, 740, 121, 31))
        self.sankey_button.setObjectName("sankey_button")
        # self.label_4 = QtWidgets.QLabel(self.tab_4)
        # self.label_4.setGeometry(QtCore.QRect(40, 40, 1501, 651))
        # self.label_4.setObjectName("label_4")
        self.browser_2 = QWebEngineView(self.tab_4)
        self.browser_2.setGeometry(QtCore.QRect(40, 40, 1500, 650))
        self.browser_2.setObjectName("web_browser_2")
        self.sankey_button.clicked.connect(self.process_4)
        self.tabWidget.addTab(self.tab_4, "")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # 退出
        self.actionquit = QtWidgets.QAction(MainWindow)
        self.actionquit.setObjectName("actionquit")
        self.actionquit.triggered.connect( QCoreApplication.instance().quit)
        # 帮助
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionhelp.triggered.connect( lambda:print( "有问题+vFlurry4g"))
        self.menu.addAction(self.actionquit)
        self.menu.addAction(self.actionhelp)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.data_process_button.setText(_translate("MainWindow", "数据预处理"))
        self.connect_button.setText(_translate("MainWindow", "连接"))
        self.db_lbl.setText(_translate("MainWindow", "数据库："))
        self.tb_lbl.setText(_translate("MainWindow", "  表： "))
        self.user_lbl.setText(_translate("MainWindow", " 用户： "))
        self.pwd_lbl.setText(_translate("MainWindow", " 密码： "))
        self.group_lda.setTitle(_translate("MainWindow", "LDA主题模型"))
        self.lda_year1_lbl.setText(_translate("MainWindow", "year1"))
        self.lda_year2_lbl.setText(_translate("MainWindow", "year2"))
        self.lda_attr_lbl.setText(_translate("MainWindow", "attr"))
        self.lda_n_topics_lbl.setText(_translate("MainWindow", "n_topics"))
        self.lda_n_top_words_lbl.setText(_translate("MainWindow", "n_top_words"))
        self.group_lda_2.setTitle(_translate("MainWindow", "困惑度曲线"))
        self.p_n_max_topics_lbl.setText(_translate("MainWindow", "n_max_topics"))
        self.group_lda_3.setTitle(_translate("MainWindow", "主题强度"))
        self.qd_year1_lbl.setText(_translate("MainWindow", "year1"))
        self.qd_year2_lbl.setText(_translate("MainWindow", "year2"))
        self.qd_year3_lbl.setText(_translate("MainWindow", "year3"))
        self.qd_year4_lbl.setText(_translate("MainWindow", "year4"))
        self.qd_dur_lbl.setText(_translate("MainWindow", "dur"))
        self.qd_n_topics_lbl.setText(_translate("MainWindow", "n_topics"))
        self.group_lda_4.setTitle(_translate("MainWindow", "相邻时间窗下主题余弦相似度"))
        self.cos_attr_lbl.setText(_translate("MainWindow", "attr"))
        self.cos_n_topics_1_lbl.setText(_translate("MainWindow", "n_topics_1"))
        self.cos_n_topics_2_lbl.setText(_translate("MainWindow", "n_topics_2"))
        self.label_5.setText(_translate("MainWindow", "时间窗"))
        self.lbl_["lbl_{}".format(self.count)].setText(_translate("MainWindow", "-"))
        self.add_button.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("MainWindow", "Tab 0"))
        self.perplexity_button.setText(_translate("MainWindow", "困惑度曲线"))
        self.lda_button.setText(_translate("MainWindow", "LDA主题模型训练"))
        self.data_process_button.setText(_translate("MainWindow", "数据预处理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Tab 1"))
        self.qiangdu_button.setText(_translate("MainWindow", "主题强度"))
        self.label_3.setText(_translate("MainWindow", "强度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.cos_button.setText(_translate("MainWindow", "主题余弦相似度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 3"))
        self.sankey_button.setText(_translate("MainWindow", "桑基图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 4"))
        self.menu.setTitle(_translate("MainWindow", "开始"))
        self.actionquit.setText(_translate("MainWindow", "退出"))
        self.actionhelp.setText(_translate("MainWindow", "帮助"))

        self.yuzhicanshu()

    # LDA 困惑度
    def process_1(self):
        # DONE_TODO 接收参数
        # user = 'root'
        # pwd = 'Xy213592'
        # db = 'patent_for_test'
        # DONE_TODO time_window 中的 表名、筛选依据的属性名（‘时间’）、起止点（2020、2021） 要额外设计控件接收
        # time_window = "SELECT * FROM `专利31000_for_test` WHERE `时间` >= 2020 AND `时间` <= 2021 "
        # n_topics = 30
        # n_top_words = 30
        # TODO n_t 用不用参数接收
        n_t = 49

        year1, year2, attr, n_topics, n_top_words, n_max_topics = self.get_para_1()
        time_window = "SELECT * FROM `{0}` WHERE `{1}` >= {2} AND `{1}` <= {3} ".format(self.tb,attr,year1,year2)

        try:
            self.x, self.y = data_process.process_1(self.user, self.pwd, self.db, time_window,n_topics,n_top_words,n_max_topics,n_t)
        except:
            QMessageBox.about(None, "提示", "检查数据库信息")
        print(self.y)
        print(self.x)

    # lda可视化
    def show_web(self):
        # FIXME 打包后可能要出事，先这么写着
        try:
            self.browser.load(QUrl("file:///D:/MyRepository/sptr/pythonProject/lda_pass30.html"))
            self.browser.show()
            print("perplexity")
        except:
            QMessageBox.about(None, "提示", "无可用资源")

    # 困惑度曲线
    def show_perplexity(self):
        print("self.y")
        print(self.y)
        if (self.y == []):
            QMessageBox.about(None, "提示", "无数据")
        else:
            # TODO 鼠标移动显示坐标
            # win = pg.GraphicsLayoutWidget(show=True, title="困惑度曲线")
            # win.resize(1000, 600)
            # Enable antialiasing for prettier plots
            # pg.setConfigOption('background', 'w')
            # pg.setConfigOptions(antialias=True)
            # p = win.addPlot(title="困惑度曲线")
            self.pw1.plot(self.y, pen=(255, 0, 0), name="curve")
            # pg.exec()

    # 主题强度
    def process_2(self):
        # DONE_TODO 补齐参数
        # user = 'root'
        # pwd = 'Xy213592'
        # db = 'patent_for_test'
        # tb = "专利31000_for_test"
        # attr = "时间"
        # year1, year2, year3, year4 = 2000, 2022, 2000, 2021
        # dur = 2
        # n_topics = 27
        year1, year2, year3, year4, dur, n_topics = self.get_para_2()
        #TODO　补attr
        qiangdu.process_2(self.user, self.pwd, self.db, self.tb, "时间", year1, year2, dur, year3, year4, n_topics)

    # 余弦相似度
    def process_3(self):
        # user = 'root'
        # pwd = 'Xy213592'
        # db = 'patent_for_test'
        # tb = "专利31000_test_2"
        # attr = "时间"
        # yr3, yr1, yr2 = 2008, 2009, 2011
        attr, n_topics_1, n_topics_2, tm_begin, tm_end = self.get_para_3()
        # TODO 多线程
        for index in range(self.count-1):
            statement1, statement2 = "",""
            if str.isdigit(tm_begin[index]) == False:
                y2 = int( tm_end[index] )
                y3 = int( tm_begin[index+1] )
                y4 = int( tm_end[index+1] )
                statement1 = "SELECT * FROM `{0}` WHERE `{1}` <= {2}  ".format(self.tb,attr,y2)
                statement2 = "SELECT * FROM `{0}` WHERE `{1}` >= {2} AND `{1}` <= {3}".format(self.tb,attr,y3,y4)
            else :
                y1 = int(tm_end[index])
                y2 = int(tm_end[index])
                y3 = int(tm_begin[index + 1])
                y4 = int(tm_end[index + 1])
                statement1 = "SELECT * FROM `{0}` WHERE `{1}` >= {2} AND `{1}` <= {3}".format(self.tb, attr, y1, y2)
                statement2 = "SELECT * FROM `{0}` WHERE `{1}` >= {2} AND `{1}` <= {3}".format(self.tb, attr, y3, y4)
            print( "i:{}".format(index))
            print( statement1)
            print( statement2)
            cos.cos_similarity(self.user, self.pwd, self.db, statement1,statement2)

    # 关联规则 桑基图
    def process_4(self):
        glgl.shuchu()
        sankey.sankey_diagram()
        self.show_web_2()

    # 展示桑吉图
    def show_web_2(self):
        # FIXME 打包后可能要出事，先这么写着
        try:
            self.browser_2.load(QUrl("file:///D:/MyRepository/sptr/pythonProject/桑基图.html"))
            self.browser_2.show()
            print("perplexity")
        except:
            QMessageBox.about(None, "提示", "无可用资源")

    # 接收参数连接数据库
    def connect_database(self):
        if self.db_ledt.text().strip()=="" or self.tb_ledt.text().strip()=="" or self.user_ledt.text().strip()=="" or self.db_ledt.text().strip()=="":
            QMessageBox.about(None, "提示", "请重新检查输入")
        else:
            self.user = self.user_ledt.text().strip()
            self.pwd = self.pwd_ledt.text().strip()
            self.db = self.db_ledt.text().strip()
            self.tb = self.tb_ledt.text().strip()
            print( self.user)
            print( self.pwd)
            print( self.db)
            print( self.tb)
            try:
                conn = pymysql.connect(host='localhost', port=3306, user=self.user, password=self.pwd, db=self.db)
                cur = conn.cursor()
                cur.execute( "SELECT * FROM `{0}`".format(self.tb) )
                cur.close()
                conn.close()
                QMessageBox.about(None, "提示", "连接成功")
                self.isconnected = True
            except:
                QMessageBox.about(None, "提示", "信息错误")
                self.user_ledt.clear()
                self.pwd_ledt.clear()
                self.db_ledt.clear()
                self.tb_ledt.clear()

    def get_para_1(self):
        try:
            year1 = self.lda_year1_ledt.text().strip()
            year2 = self.lda_year2_ledt.text().strip()
            attr = self.lda_attr_ledt.text().strip()
            n_topics = self.lda_n_topics_ledt.text().strip()
            n_top_words = self.lda_n_top_words_ledt.text().strip()
            n_max_topics = self.p_n_max_topics_ledt.text().strip()
            return year1,year2,attr,n_topics,n_top_words,n_max_topics
        except:
            QMessageBox.about(None, "提示", "检查数据")

    def get_para_2(self):
        try:
            year1,year2,year3,year4 = self.qd_year1_ledt.text().strip(),self.qd_year2_ledt.text().strip(),self.qd_year3_ledt.text().strip(),self.qd_year4_ledt.text().strip()
            dur = self.qd_dur_ledt.text().strip()
            n_topics = self.lda_n_topics_ledt.text().strip()
            return year1,year2,year3,year4,dur,n_topics
        except:
            QMessageBox.about(None, "提示", "检查数据")

    def get_para_3(self):
        # TODO 时间窗参数接收
        try:
            attr = self.cos_attr_ledt.text().strip()
            n_topics_1 = self.cos_n_topics_1_ledt.text().strip()
            n_topics_2 = self.cos_n_topics_2_ledt.text().strip()
            tm_begin, tm_end = [], []
            for i in range(self.count):
                tm_begin.append( (self.lineEdit_begin["lineEdit_begin_{}".format(i + 1)]).text().strip())
                tm_end.append( (self.lineEdit_end["lineEdit_end_{}".format(i+1)]).text().strip() )
            print( tm_begin )
            print( tm_end )
            return attr,n_topics_1,n_topics_2,tm_begin,tm_end
        except:
            QMessageBox.about(None, "提示", "检查数据")

    def add_interval(self):
        self.count += 1
        _translate = QtCore.QCoreApplication.translate
        interval_layout_1 = QtWidgets.QHBoxLayout()
        spacerItem58 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        interval_layout_1.addItem(spacerItem58)
        self.lineEdit_begin["lineEdit_begin_{}".format(self.count)] = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_begin["lineEdit_begin_{}".format(self.count)].setObjectName(
            "lineEdit_begin_{}".format(self.count ))
        interval_layout_1.addWidget(self.lineEdit_begin["lineEdit_begin_{}".format(self.count )])
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        interval_layout_1.addItem(spacerItem59)
        self.lbl_["lbl_{}".format(self.count )] = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_["lbl_{}".format(self.count )].setObjectName(
            "lbl_{}".format(self.count ))
        self.lbl_["lbl_{}".format(self.count )].setText(_translate("MainWindow", "-"))
        interval_layout_1.addWidget(self.lbl_["lbl_{}".format(self.count)])
        spacerItem60 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        interval_layout_1.addItem(spacerItem60)
        self.lineEdit_end["lineEdit_end_{}".format(self.count )] = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_end["lineEdit_end_{}".format(self.count)].setObjectName(
            "lineEdit_end_{}".format(self.count))
        interval_layout_1.addWidget(self.lineEdit_begin["lineEdit_end_{}".format(self.count)])
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        interval_layout_1.addItem(spacerItem61)
        self.time_window_layout.addLayout(interval_layout_1)
        self.time_window_layout.addLayout(interval_layout_1)


    # 参数预置，省得手打
    def yuzhicanshu(self):
        self.user_ledt.setText('root')
        self.pwd_ledt.setText('Xy213592')
        self.db_ledt.setText('patent_for_test')
        self.tb_ledt.setText('专利31000_test_2')

        self.lda_year1_ledt.setText("2020")
        self.lda_year2_ledt.setText("2021")
        self.lda_attr_ledt.setText("时间")
        self.lda_n_topics_ledt.setText("30")
        self.lda_n_top_words_ledt.setText("30")
        self.p_n_max_topics_ledt.setText("50")

        self.qd_year1_ledt.setText("2000")
        self.qd_year2_ledt.setText("2022")
        self.qd_year3_ledt.setText("2000")
        self.qd_year4_ledt.setText("2021")
        self.qd_dur_ledt.setText("2")
        self.qd_n_topics_ledt.setText("27")

        self.cos_attr_ledt.setText("时间")
        self.cos_n_topics_1_ledt.setText("21")
        self.cos_n_topics_2_ledt.setText("19")